[package]
name = "rusty_capybara"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
od_opencv = "0.1.5"
opencv = "0.88.9"
rppal = "0.17.1"
